version: 2
# represents a list of jobs that will be run
jobs:
# Tells circleCi to use a machine executer
  build:
    machine:
      image: circleci/classic:201808-01
    # specifies all the commands that will be executed during this build
    steps:
    # perform a git clone into the build environment
      - checkout
        # specify commands to execute within the build
      - run:
        # change file ownership 
          name: change file ownership
          command: sudo chown -R $USER:$USER .
    
      - run:
      #  build the image
          name : build the image 
          command:
            docker-compose up --build 
