version: 2
# represents a list of jobs that will be run
jobs:
# Tells circleCi to use a machine executer
  build:
    machine: true
    # specifies all the commands that will be executed during this build
    steps:
    # perform a git clone into the build environment
      - checkout
      # Permission Denied When Creating Directory or Writing a File
      - run: chown -R $USER:$USER tmp/
      # specify commands to execute within the build
      - run:
          name : build the image and run test
          command: |
            docker-compose up --build -d
            docker-compose run app rails test
